### PR TITLE
Fix lifestyle_physician #71

### PR DESCRIPTION
**Pull request by NicolasGrosjean**
lifestyle_physician is not given so I increase the physician level instead.

But like lifestyle_physician was already in the trigger, it might be a copy-paste error. It this case, do not hesitate to remove my code.

### CODE REVIEW

**Comment by cybrxkhan** [comment]
Thanks for the heads up - my intention was to have it so that the game shows that you had this option triggered because you have the Physician trait, rather than to increase the physician trait. I suppose that's not possible then with one line and I'll have to split it up? (At least that I know of)

(Though, now that I think about it, having it so you increase your physician trait thanks to this event makes sense so I'll add that in)

**Comment by NicolasGrosjean** [comment]
Ah I have mixed _add_trait_ with the _trait_ option discovered in [the wiki.](https://ck3.paradoxwikis.com/Event_modding#Options).

Split the option for each physician trait is a good idea to show the option available by the trait, I can improve my pull request next week.

**Comment by cybrxkhan** [comment]
No worries, I've revised it myself and just uploaded the changes - thanks for catching it!

**Comment by NicolasGrosjean** [comment]
Thank you.

**Pull request closed without merging**
